apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu:latest
            args:
            - /bin/sh
            - -c
            - date; echo Byebye from the Kubernetes cluster
          restartPolicy: OnFailure