apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: kube-system
subjects:
- kind: User
  name: alice
  apiGroup: ""
roleRef:
  kind: Role
  name: my-role
  apiGroup: ""